// Code generated by protoc-gen-go. DO NOT EDIT.
// source: organisations.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrganisationPermissions_Access int32

const (
	OrganisationPermissions_UNKNOWN_ACCESS  OrganisationPermissions_Access = 0
	OrganisationPermissions_NO_MEMBERSHIP   OrganisationPermissions_Access = 1
	OrganisationPermissions_INVITATION_ONLY OrganisationPermissions_Access = 2
	OrganisationPermissions_ON_REQUEST      OrganisationPermissions_Access = 3
)

var OrganisationPermissions_Access_name = map[int32]string{
	0: "UNKNOWN_ACCESS",
	1: "NO_MEMBERSHIP",
	2: "INVITATION_ONLY",
	3: "ON_REQUEST",
}

var OrganisationPermissions_Access_value = map[string]int32{
	"UNKNOWN_ACCESS":  0,
	"NO_MEMBERSHIP":   1,
	"INVITATION_ONLY": 2,
	"ON_REQUEST":      3,
}

func (x OrganisationPermissions_Access) String() string {
	return proto.EnumName(OrganisationPermissions_Access_name, int32(x))
}

func (OrganisationPermissions_Access) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cbb7588f37235369, []int{2, 0}
}

type Grant struct {
	OrganisationId       []byte   `protobuf:"bytes,1,opt,name=organisation_id,json=organisationId,proto3" json:"organisation_id,omitempty"`
	MemberId             []byte   `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	ChatId               string   `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Clock                uint64   `protobuf:"varint,4,opt,name=clock,proto3" json:"clock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Grant) Reset()         { *m = Grant{} }
func (m *Grant) String() string { return proto.CompactTextString(m) }
func (*Grant) ProtoMessage()    {}
func (*Grant) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbb7588f37235369, []int{0}
}

func (m *Grant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Grant.Unmarshal(m, b)
}
func (m *Grant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Grant.Marshal(b, m, deterministic)
}
func (m *Grant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Grant.Merge(m, src)
}
func (m *Grant) XXX_Size() int {
	return xxx_messageInfo_Grant.Size(m)
}
func (m *Grant) XXX_DiscardUnknown() {
	xxx_messageInfo_Grant.DiscardUnknown(m)
}

var xxx_messageInfo_Grant proto.InternalMessageInfo

func (m *Grant) GetOrganisationId() []byte {
	if m != nil {
		return m.OrganisationId
	}
	return nil
}

func (m *Grant) GetMemberId() []byte {
	if m != nil {
		return m.MemberId
	}
	return nil
}

func (m *Grant) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *Grant) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

type ChatMessageIdentity struct {
	// stubbing this, it's already been prepared in a different PR
	EnsName              string   `protobuf:"bytes,1,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	ProfilePicture       string   `protobuf:"bytes,2,opt,name=profile_picture,json=profilePicture,proto3" json:"profile_picture,omitempty"`
	DisplayName          string   `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessageIdentity) Reset()         { *m = ChatMessageIdentity{} }
func (m *ChatMessageIdentity) String() string { return proto.CompactTextString(m) }
func (*ChatMessageIdentity) ProtoMessage()    {}
func (*ChatMessageIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbb7588f37235369, []int{1}
}

func (m *ChatMessageIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessageIdentity.Unmarshal(m, b)
}
func (m *ChatMessageIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessageIdentity.Marshal(b, m, deterministic)
}
func (m *ChatMessageIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessageIdentity.Merge(m, src)
}
func (m *ChatMessageIdentity) XXX_Size() int {
	return xxx_messageInfo_ChatMessageIdentity.Size(m)
}
func (m *ChatMessageIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessageIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessageIdentity proto.InternalMessageInfo

func (m *ChatMessageIdentity) GetEnsName() string {
	if m != nil {
		return m.EnsName
	}
	return ""
}

func (m *ChatMessageIdentity) GetProfilePicture() string {
	if m != nil {
		return m.ProfilePicture
	}
	return ""
}

func (m *ChatMessageIdentity) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ChatMessageIdentity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type OrganisationPermissions struct {
	EnsOnly          bool `protobuf:"varint,1,opt,name=ens_only,json=ensOnly,proto3" json:"ens_only,omitempty"`
	CanRequestAccess bool `protobuf:"varint,2,opt,name=can_request_access,json=canRequestAccess,proto3" json:"can_request_access,omitempty"`
	// https://gitlab.matrix.org/matrix-org/olm/blob/master/docs/megolm.md is a candidate for the algorithm to be used in case we want to have private organisational chats, lighter than pairwise encryption using the DR, less secure, but more efficient for large number of participants
	Private              bool                           `protobuf:"varint,3,opt,name=private,proto3" json:"private,omitempty"`
	Access               OrganisationPermissions_Access `protobuf:"varint,4,opt,name=access,proto3,enum=protobuf.OrganisationPermissions_Access" json:"access,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *OrganisationPermissions) Reset()         { *m = OrganisationPermissions{} }
func (m *OrganisationPermissions) String() string { return proto.CompactTextString(m) }
func (*OrganisationPermissions) ProtoMessage()    {}
func (*OrganisationPermissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbb7588f37235369, []int{2}
}

func (m *OrganisationPermissions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganisationPermissions.Unmarshal(m, b)
}
func (m *OrganisationPermissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganisationPermissions.Marshal(b, m, deterministic)
}
func (m *OrganisationPermissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganisationPermissions.Merge(m, src)
}
func (m *OrganisationPermissions) XXX_Size() int {
	return xxx_messageInfo_OrganisationPermissions.Size(m)
}
func (m *OrganisationPermissions) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganisationPermissions.DiscardUnknown(m)
}

var xxx_messageInfo_OrganisationPermissions proto.InternalMessageInfo

func (m *OrganisationPermissions) GetEnsOnly() bool {
	if m != nil {
		return m.EnsOnly
	}
	return false
}

func (m *OrganisationPermissions) GetCanRequestAccess() bool {
	if m != nil {
		return m.CanRequestAccess
	}
	return false
}

func (m *OrganisationPermissions) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

func (m *OrganisationPermissions) GetAccess() OrganisationPermissions_Access {
	if m != nil {
		return m.Access
	}
	return OrganisationPermissions_UNKNOWN_ACCESS
}

type OrganisationDescription struct {
	Clock                uint64                   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Members              [][]byte                 `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	Permissions          *OrganisationPermissions `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Identity             *ChatMessageIdentity     `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	Chats                []*OrganisationChat      `protobuf:"bytes,6,rep,name=chats,proto3" json:"chats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *OrganisationDescription) Reset()         { *m = OrganisationDescription{} }
func (m *OrganisationDescription) String() string { return proto.CompactTextString(m) }
func (*OrganisationDescription) ProtoMessage()    {}
func (*OrganisationDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbb7588f37235369, []int{3}
}

func (m *OrganisationDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganisationDescription.Unmarshal(m, b)
}
func (m *OrganisationDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganisationDescription.Marshal(b, m, deterministic)
}
func (m *OrganisationDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganisationDescription.Merge(m, src)
}
func (m *OrganisationDescription) XXX_Size() int {
	return xxx_messageInfo_OrganisationDescription.Size(m)
}
func (m *OrganisationDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganisationDescription.DiscardUnknown(m)
}

var xxx_messageInfo_OrganisationDescription proto.InternalMessageInfo

func (m *OrganisationDescription) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *OrganisationDescription) GetMembers() [][]byte {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *OrganisationDescription) GetPermissions() *OrganisationPermissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *OrganisationDescription) GetIdentity() *ChatMessageIdentity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *OrganisationDescription) GetChats() []*OrganisationChat {
	if m != nil {
		return m.Chats
	}
	return nil
}

type OrganisationChat struct {
	ChatId               string                   `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Clock                uint64                   `protobuf:"varint,2,opt,name=clock,proto3" json:"clock,omitempty"`
	Members              [][]byte                 `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	Permissions          *OrganisationPermissions `protobuf:"bytes,4,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Identity             *ChatMessageIdentity     `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *OrganisationChat) Reset()         { *m = OrganisationChat{} }
func (m *OrganisationChat) String() string { return proto.CompactTextString(m) }
func (*OrganisationChat) ProtoMessage()    {}
func (*OrganisationChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbb7588f37235369, []int{4}
}

func (m *OrganisationChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganisationChat.Unmarshal(m, b)
}
func (m *OrganisationChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganisationChat.Marshal(b, m, deterministic)
}
func (m *OrganisationChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganisationChat.Merge(m, src)
}
func (m *OrganisationChat) XXX_Size() int {
	return xxx_messageInfo_OrganisationChat.Size(m)
}
func (m *OrganisationChat) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganisationChat.DiscardUnknown(m)
}

var xxx_messageInfo_OrganisationChat proto.InternalMessageInfo

func (m *OrganisationChat) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *OrganisationChat) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *OrganisationChat) GetMembers() [][]byte {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *OrganisationChat) GetPermissions() *OrganisationPermissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *OrganisationChat) GetIdentity() *ChatMessageIdentity {
	if m != nil {
		return m.Identity
	}
	return nil
}

type OrganisationInvitation struct {
	Organisation         *OrganisationDescription `protobuf:"bytes,1,opt,name=organisation,proto3" json:"organisation,omitempty"`
	Grant                []byte                   `protobuf:"bytes,2,opt,name=grant,proto3" json:"grant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *OrganisationInvitation) Reset()         { *m = OrganisationInvitation{} }
func (m *OrganisationInvitation) String() string { return proto.CompactTextString(m) }
func (*OrganisationInvitation) ProtoMessage()    {}
func (*OrganisationInvitation) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbb7588f37235369, []int{5}
}

func (m *OrganisationInvitation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganisationInvitation.Unmarshal(m, b)
}
func (m *OrganisationInvitation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganisationInvitation.Marshal(b, m, deterministic)
}
func (m *OrganisationInvitation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganisationInvitation.Merge(m, src)
}
func (m *OrganisationInvitation) XXX_Size() int {
	return xxx_messageInfo_OrganisationInvitation.Size(m)
}
func (m *OrganisationInvitation) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganisationInvitation.DiscardUnknown(m)
}

var xxx_messageInfo_OrganisationInvitation proto.InternalMessageInfo

func (m *OrganisationInvitation) GetOrganisation() *OrganisationDescription {
	if m != nil {
		return m.Organisation
	}
	return nil
}

func (m *OrganisationInvitation) GetGrant() []byte {
	if m != nil {
		return m.Grant
	}
	return nil
}

type OrganisationRequestJoin struct {
	EnsName              string   `protobuf:"bytes,1,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	ChatId               string   `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	OrganisationId       []byte   `protobuf:"bytes,3,opt,name=organisation_id,json=organisationId,proto3" json:"organisation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrganisationRequestJoin) Reset()         { *m = OrganisationRequestJoin{} }
func (m *OrganisationRequestJoin) String() string { return proto.CompactTextString(m) }
func (*OrganisationRequestJoin) ProtoMessage()    {}
func (*OrganisationRequestJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbb7588f37235369, []int{6}
}

func (m *OrganisationRequestJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganisationRequestJoin.Unmarshal(m, b)
}
func (m *OrganisationRequestJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganisationRequestJoin.Marshal(b, m, deterministic)
}
func (m *OrganisationRequestJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganisationRequestJoin.Merge(m, src)
}
func (m *OrganisationRequestJoin) XXX_Size() int {
	return xxx_messageInfo_OrganisationRequestJoin.Size(m)
}
func (m *OrganisationRequestJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganisationRequestJoin.DiscardUnknown(m)
}

var xxx_messageInfo_OrganisationRequestJoin proto.InternalMessageInfo

func (m *OrganisationRequestJoin) GetEnsName() string {
	if m != nil {
		return m.EnsName
	}
	return ""
}

func (m *OrganisationRequestJoin) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *OrganisationRequestJoin) GetOrganisationId() []byte {
	if m != nil {
		return m.OrganisationId
	}
	return nil
}

type OrganisationRequestJoinResponse struct {
	Organisation         *OrganisationDescription `protobuf:"bytes,1,opt,name=organisation,proto3" json:"organisation,omitempty"`
	Accepted             bool                     `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Grant                []byte                   `protobuf:"bytes,3,opt,name=grant,proto3" json:"grant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *OrganisationRequestJoinResponse) Reset()         { *m = OrganisationRequestJoinResponse{} }
func (m *OrganisationRequestJoinResponse) String() string { return proto.CompactTextString(m) }
func (*OrganisationRequestJoinResponse) ProtoMessage()    {}
func (*OrganisationRequestJoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbb7588f37235369, []int{7}
}

func (m *OrganisationRequestJoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganisationRequestJoinResponse.Unmarshal(m, b)
}
func (m *OrganisationRequestJoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganisationRequestJoinResponse.Marshal(b, m, deterministic)
}
func (m *OrganisationRequestJoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganisationRequestJoinResponse.Merge(m, src)
}
func (m *OrganisationRequestJoinResponse) XXX_Size() int {
	return xxx_messageInfo_OrganisationRequestJoinResponse.Size(m)
}
func (m *OrganisationRequestJoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganisationRequestJoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrganisationRequestJoinResponse proto.InternalMessageInfo

func (m *OrganisationRequestJoinResponse) GetOrganisation() *OrganisationDescription {
	if m != nil {
		return m.Organisation
	}
	return nil
}

func (m *OrganisationRequestJoinResponse) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

func (m *OrganisationRequestJoinResponse) GetGrant() []byte {
	if m != nil {
		return m.Grant
	}
	return nil
}

func init() {
	proto.RegisterEnum("protobuf.OrganisationPermissions_Access", OrganisationPermissions_Access_name, OrganisationPermissions_Access_value)
	proto.RegisterType((*Grant)(nil), "protobuf.Grant")
	proto.RegisterType((*ChatMessageIdentity)(nil), "protobuf.ChatMessageIdentity")
	proto.RegisterType((*OrganisationPermissions)(nil), "protobuf.OrganisationPermissions")
	proto.RegisterType((*OrganisationDescription)(nil), "protobuf.OrganisationDescription")
	proto.RegisterType((*OrganisationChat)(nil), "protobuf.OrganisationChat")
	proto.RegisterType((*OrganisationInvitation)(nil), "protobuf.OrganisationInvitation")
	proto.RegisterType((*OrganisationRequestJoin)(nil), "protobuf.OrganisationRequestJoin")
	proto.RegisterType((*OrganisationRequestJoinResponse)(nil), "protobuf.OrganisationRequestJoinResponse")
}

func init() { proto.RegisterFile("organisations.proto", fileDescriptor_cbb7588f37235369) }

var fileDescriptor_cbb7588f37235369 = []byte{
	// 620 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xfe, 0x39, 0x6e, 0x52, 0x67, 0x92, 0x5f, 0x6a, 0xb6, 0x88, 0x86, 0x22, 0x44, 0xea, 0x0b,
	0x3e, 0xa0, 0x08, 0x95, 0x13, 0x37, 0x4a, 0xb0, 0xc0, 0x40, 0xed, 0xb2, 0x49, 0x41, 0x9c, 0xac,
	0xad, 0xbd, 0x6d, 0x57, 0x24, 0x6b, 0xe3, 0xdd, 0x54, 0x8a, 0xc4, 0x63, 0x70, 0xe2, 0xc0, 0x8b,
	0xf1, 0x28, 0x5c, 0xd0, 0xae, 0x9d, 0xda, 0x41, 0x49, 0xb9, 0x20, 0x4e, 0xf6, 0xcc, 0xce, 0x9f,
	0x6f, 0xbe, 0xfd, 0x76, 0x60, 0x37, 0xcd, 0x2f, 0x08, 0x67, 0x82, 0x48, 0x96, 0x72, 0x31, 0xcc,
	0xf2, 0x54, 0xa6, 0xc8, 0xd2, 0x9f, 0xb3, 0xf9, 0xb9, 0xf3, 0x05, 0x9a, 0x2f, 0x73, 0xc2, 0x25,
	0x7a, 0x08, 0x3b, 0xf5, 0xc8, 0x88, 0x25, 0x7d, 0x63, 0x60, 0xb8, 0x5d, 0xdc, 0xab, 0xbb, 0xfd,
	0x04, 0xdd, 0x83, 0xf6, 0x8c, 0xce, 0xce, 0x68, 0xae, 0x42, 0x1a, 0x3a, 0xc4, 0x2a, 0x1c, 0x7e,
	0x82, 0xf6, 0x60, 0x3b, 0xbe, 0x24, 0x52, 0x1d, 0x99, 0x03, 0xc3, 0x6d, 0xe3, 0x96, 0x32, 0xfd,
	0x04, 0xdd, 0x86, 0x66, 0x3c, 0x4d, 0xe3, 0x4f, 0xfd, 0xad, 0x81, 0xe1, 0x6e, 0xe1, 0xc2, 0x70,
	0xbe, 0x1b, 0xb0, 0x3b, 0xba, 0x24, 0xf2, 0x98, 0x0a, 0x41, 0x2e, 0xa8, 0x9f, 0x50, 0x2e, 0x99,
	0x5c, 0xa0, 0xbb, 0x60, 0x51, 0x2e, 0x22, 0x4e, 0x66, 0x54, 0xa3, 0x68, 0xe3, 0x6d, 0xca, 0x45,
	0x40, 0x66, 0x54, 0xe1, 0xcc, 0xf2, 0xf4, 0x9c, 0x4d, 0x69, 0x94, 0xb1, 0x58, 0xce, 0x73, 0xaa,
	0x41, 0xb4, 0x71, 0xaf, 0x74, 0x9f, 0x14, 0x5e, 0x74, 0x00, 0xdd, 0x84, 0x89, 0x6c, 0x4a, 0x16,
	0x45, 0x9d, 0x02, 0x4f, 0xa7, 0xf4, 0xe9, 0x5a, 0x03, 0xe8, 0x24, 0x54, 0xc4, 0x39, 0xcb, 0xd4,
	0x6c, 0x1a, 0x9a, 0x8a, 0xa8, 0x5c, 0xce, 0xd7, 0x06, 0xec, 0x85, 0xb5, 0xf9, 0x4f, 0x68, 0x3e,
	0x63, 0x42, 0x28, 0x2a, 0x97, 0x20, 0x53, 0x3e, 0x5d, 0x68, 0x90, 0x96, 0x06, 0x19, 0xf2, 0xe9,
	0x02, 0x3d, 0x02, 0x14, 0x13, 0x1e, 0xe5, 0xf4, 0xf3, 0x9c, 0x0a, 0x19, 0x91, 0x38, 0xa6, 0x42,
	0x68, 0x9c, 0x16, 0xb6, 0x63, 0xc2, 0x71, 0x71, 0x70, 0xa4, 0xfd, 0xa8, 0x0f, 0xdb, 0x59, 0xce,
	0xae, 0x88, 0x2c, 0x40, 0x5a, 0x78, 0x69, 0xa2, 0x67, 0xd0, 0x2a, 0x73, 0x15, 0xb6, 0xde, 0xa1,
	0x3b, 0x5c, 0x5e, 0xdc, 0x70, 0x03, 0xaa, 0x61, 0x51, 0x13, 0x97, 0x79, 0xce, 0x04, 0x5a, 0x65,
	0x17, 0x04, 0xbd, 0xd3, 0xe0, 0x4d, 0x10, 0x7e, 0x08, 0xa2, 0xa3, 0xd1, 0xc8, 0x1b, 0x8f, 0xed,
	0xff, 0xd0, 0x2d, 0xf8, 0x3f, 0x08, 0xa3, 0x63, 0xef, 0xf8, 0xb9, 0x87, 0xc7, 0xaf, 0xfc, 0x13,
	0xdb, 0x40, 0xbb, 0xb0, 0xe3, 0x07, 0xef, 0xfd, 0xc9, 0xd1, 0xc4, 0x0f, 0x83, 0x28, 0x0c, 0xde,
	0x7e, 0xb4, 0x1b, 0xa8, 0x07, 0x10, 0x06, 0x11, 0xf6, 0xde, 0x9d, 0x7a, 0xe3, 0x89, 0x6d, 0x3a,
	0x3f, 0x8d, 0x55, 0x5a, 0x5e, 0x54, 0x94, 0x55, 0x37, 0x6d, 0xd4, 0x6e, 0x5a, 0xcd, 0x58, 0x88,
	0x44, 0xd1, 0x60, 0xba, 0x5d, 0xbc, 0x34, 0xd1, 0x08, 0x3a, 0x59, 0x85, 0x5f, 0x33, 0xd0, 0x39,
	0x3c, 0xf8, 0xe3, 0xa0, 0xb8, 0x9e, 0x85, 0x9e, 0x82, 0xc5, 0x4a, 0xf1, 0xf4, 0x9b, 0xba, 0xc2,
	0xfd, 0xaa, 0xc2, 0x1a, 0x85, 0xe1, 0xeb, 0x70, 0xf4, 0x18, 0x9a, 0x4a, 0xa3, 0xa2, 0xdf, 0x1a,
	0x98, 0x6e, 0xe7, 0x70, 0x7f, 0x7d, 0x67, 0x55, 0x03, 0x17, 0x81, 0xce, 0x0f, 0x03, 0xec, 0xdf,
	0xcf, 0xea, 0xca, 0x37, 0xd6, 0x2b, 0xbf, 0xb1, 0x81, 0x0f, 0xf3, 0x46, 0x3e, 0xb6, 0xfe, 0x31,
	0x1f, 0xce, 0x1c, 0xee, 0xd4, 0x5b, 0xf8, 0xfc, 0x8a, 0x49, 0xfd, 0x87, 0x3c, 0xe8, 0xd6, 0x77,
	0x81, 0x9e, 0x73, 0x23, 0xb4, 0x9a, 0x24, 0xf0, 0x4a, 0x9a, 0x22, 0xe4, 0x42, 0xad, 0x9c, 0x72,
	0x79, 0x14, 0x86, 0x73, 0xb5, 0xaa, 0xa8, 0xf2, 0x85, 0xbc, 0x4e, 0x19, 0xbf, 0x69, 0x1b, 0xd4,
	0x58, 0x6f, 0xac, 0xb0, 0xbe, 0x66, 0x9d, 0x99, 0xeb, 0xd6, 0x99, 0xf3, 0xcd, 0x80, 0x07, 0x1b,
	0x1a, 0x63, 0x2a, 0xb2, 0x94, 0x0b, 0xfa, 0xb7, 0x06, 0xdf, 0x07, 0x4b, 0xbd, 0xca, 0x4c, 0xd2,
	0xa4, 0xdc, 0x05, 0xd7, 0x76, 0x45, 0x8a, 0x59, 0x23, 0xe5, 0xac, 0xa5, 0x3b, 0x3c, 0xf9, 0x15,
	0x00, 0x00, 0xff, 0xff, 0x5f, 0x1b, 0xce, 0x7e, 0xc5, 0x05, 0x00, 0x00,
}
